# Generated by Django 2.2 on 2020-02-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_app', '0003_user_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('cat1', models.CharField(blank=True, max_length=25)),
                ('cat2', models.CharField(blank=True, max_length=25)),
                ('image', models.CharField(max_length=50)),
                ('in_stock', models.SmallIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favorited_by', models.ManyToManyField(related_name='favorites', to='login_app.User')),
            ],
        ),
    ]
